### ISSUE TITLE
Demo command 

### ISSUE THREAD

**Issue by JeonghyunNam** [ZhengyiLuo/PULSE#1]
Hello! 
Thanks for sharing your great work

I want to run your code with motions that aren't standing still motion.
Could you share the command for that?

**Comment by ZhengyiLuo** [comment]
Please see [here](https://github.com/ZhengyiLuo/PULSE?tab=readme-ov-file#run-pulse)

"Press M (disable termination), and press I (start sampling), to see ramdomly sampled motion."
