### ISSUE TITLE
关于力控方法control_mode: "isaac_pd"

### ISSUE THREAD

**Issue by Anonnyyy** [ZhengyiLuo/PULSE#13]
您好！感谢分享！
1.我看到目前计算关节扭矩的方法（"isaac_pd"）是将action decoder后得到期望关节位置，调用gym的内部方法gym.set_dof_position_target_tensor(self.sim, pd_tar_tensor)实现控制，而不是自行计算扭矩。请问我理解的是否正确？
2.另外，看到code里提供了"pd"、''force"等计算扭矩的方法，请问是可以使用的吗？是否需要额外步骤？我将"isaac_pd"更改为"pd"后，机器人无法完成控制、会摔倒。

**Comment by ZhengyiLuo** [comment]
1. Yes. 
2. If you use those control method, the police needs to be retrained (starting from PHC).
