### ISSUE TITLE
Question about the regulerlization term.

### ISSUE THREAD

**Issue by LinghaoChan** [ZhengyiLuo/PULSE#2]
Hi @ZhengyiLuo , I have a question about the vae distillation. I notice there exist a term of ar1_prior [here](https://github.com/ZhengyiLuo/PULSE/blob/769b6f6013109aab365d8312ca7c6714ed413596/phc/learning/amp_agent.py#L792-L808). I checked the original paper from Josh Merel. To my own understanding, this term aims to make neighbors' actions similar. Is it right? I am a bit confused about the term of `kin_dict['progress_buf']`. What does it refer to and when is it assigned values? 

If you could provide any guides, I would appreciate it! (^_^)

Thanks.

Evan

**Comment by ZhengyiLuo** [comment]
The progress_buf is the time step for the episode; it provides the information if the actions are taken as neighbor of each other.
