### ISSUE TITLE
Question: CMD for Scratch and Evaluation of PHC+

### ISSUE THREAD

**Issue by Rowing0914** [ZhengyiLuo/PULSE#3]
Hi @ZhengyiLuo thank you for publishing the codebase. can you tell me how to run the scratch agent and how to evaluate the imitation performance of just PHC+?

**Comment by ZhengyiLuo** [comment]
For just PHC+, you can go to the [PHC](https://github.com/ZhengyiLuo/PHC) repo. The code & models are updated there for running PHC+.
