### ISSUE TITLE
Question: CMD/Procedure to reproduce your result (Table 2)

### ISSUE THREAD

**Issue by Rowing0914** [ZhengyiLuo/PULSE#4]
@ZhengyiLuo Hi, can you provide the full procedures or cmds to reproduce Table 2? thanks.

**Comment by ZhengyiLuo** [comment]
Table 2? The VR controller tracking one?

**Comment by Rowing0914** [comment]
yes, Table 2. Could you please provide the command or evaluation code specifically for TABLE 2?

**Comment by Rowing0914** [comment]
![image](https://github.com/user-attachments/assets/f1e19766-03b6-446d-889f-92cb69cc9e66)

**Comment by ZhengyiLuo** [comment]
Commands for training PULSE for the VR controller task have been released.

**Comment by Rowing0914** [comment]
Thanks!
