### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by soungsill** [ZhengyiLuo/PULSE#5]
When trying to run the code, the error occurred: How should I handle it?

When I ran the example to check for isaacgym installation errors, I confirmed that it worked well.

An error occurs in the part marked in bold in the base_task.py file.

******* base_task.py ***********
if self.enable_viewer_sync:
    self.gym.step_graphics(self.sim)
    **self.gym.draw_viewer(self.viewer, self.sim, True)** 
    #self.gym.sync_frame_time(self.sim)

else:
    self.gym.poll_viewer_events(self.viewer)
***************************************

+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
!!!! Using modified SMPL starting pose !!!!
Humanoid Weights [63.313948929309845]

****************************** Current motion keys ******************************
Sampling motion: tensor([0], device='cuda:0')
standing
*********************************************************************************

0it [00:00, ?it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27060.03it/s]
Loaded 1 motions with a total length of 33.300s and 1000 frames.
#################### Generating Fall State ####################
Segmentation fault (core dumped)

**Comment by ZhengyiLuo** [comment]
This looks like the viewer has an error launching; does Isaacgym launch well on your end? 

If so, try no_virtual_display=True in the command.
